<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.ramon-rabello</groupId> 
    <artifactId>exercicio-junit-ramon-rabello</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>5.10.1</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.pitest</groupId>
                <artifactId>pitest-maven</artifactId>
                <version>1.15.0</version>
                <dependencies>
                    <dependency>
                        <groupId>org.pitest</groupId>
                        <artifactId>pitest-junit5-plugin</artifactId>
                        <version>1.2.1</version>
                    </dependency>
                </dependencies>
                <configuration>
                    <targetClasses>
                        <param>carrinho.*</param>
                        <param>produto.*</param>
                        <param>calculadora.*</param>
                        <param>jokenpo.*</param>
                        <param>basico.*</param>
                    </targetClasses>
                    <targetTests>
                        <param>*Test</param>
                    </targetTests>
                    <reportsDirectory>target/pit-reports-manuais</reportsDirectory>
                </configuration>
                <!-- <configuration>
                    <targetClasses>
                        <param>carrinho.*</param>
                        <param>produto.*</param>
                        <param>calculadora.*</param>
                        <param>jokenpo.*</param>
                        <param>basico.*</param>
                    </targetClasses>
                    <targetTests>
                        <param>*TestGpt</param>
                    </targetTests>
                    <reportsDirectory>target/pit-reports-gpt</reportsDirectory>
                </configuration> -->
            </plugin>
        </plugins>
    </build>
</project>